<?php

namespace AppBundle\Repository;

/**
 * PostalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostalRepository extends \Doctrine\ORM\EntityRepository
{
}
